### ISSUE TITLE
Mejorar los datos por defecto

### ISSUE THREAD

**Issue by Avendaosander** [Avendaosander/API-Eventos-UVM#2]
## Tasks
***

- [ ] Colocar los datos del administrador por defecto en variables de entorno
- [ ] Colocar el creador de los eventos por defecto en variable de entorno
- [ ] Modificar las imagenes de todos los eventos por defecto
- [ ] Modificar las descripciones de todos los eventos por defecto
- [ ] Modificar los lugares de todos los eventos por defecto
- [ ] Modificar la hora de algunos eventos por defecto
- [ ] Modificar la fecha de algunos eventos por defecto
