### ISSUE TITLE
Autenticar Rutas

### ISSUE THREAD

**Issue by Avendaosander** [Avendaosander/API-Eventos-UVM#5]
## Tasks
***
- [ ] Crear middleware para autenticar rutas a traves de un header con un token
- [ ] Decodificar token con JWT
- [ ] Comprobar si el token decodificado es igual al ID de un usuario en la Base de Datos de los Usuarios
- [ ] Agregar manejo de errores
### Rutas que deben ser Protegidas

- `/auth/register-admin/:adminID`
- `/app/dashboard`
- `/app/events`
- `/app/old-events`
- `/app/filters`
- `/app/toggle-favorite/:eventID`
- `/app/favorites/:userID`
- `/app/my-events/:adminID`
- `/app/profile/:userID`
- `/app/update-profile/:userID`
- `/events/event/:eventID`
- `/events/toggle-asist/:userID`
- `/events/create-event/:userID`
- `/events/update-event/:eventID`
- `/events/delete-event/:eventID`
